server:
  port: 8081

warehouse:
  id: warehouse-1
  temperature-port: 3344
  humidity-port: 3355

# Kafka Properties
spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic: sensor-readings
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
